- year: 2025
  role: "Reviewer"
  description: "Reviewed one paper for the Journal of Computer Security"

- year: 2025
  role: "Reviewer"
  description: "Reviewed four papers for the Journal of Information Security and Applications"

- year: 2025
  role: "Reviewer"
  description: "Reviewed two papers for the Journal IEEE Transactions on Information Forensics and Security (IEEE TIFS)"
